services:
  flappy-dragon:
    image: flappy-dragon:latest
    container_name: flappy-dragon
    ports:
      - "127.0.0.1:8006:80"
    mem_limit: 32m
    restart: unless-stopped
    depends_on:
      - flappy-scores

  flappy-scores:
    image: flappy-scores:latest
    container_name: flappy-scores
    volumes:
      - /opt/flappy-dragon:/data
    mem_limit: 16m
    restart: unless-stopped
