server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Required MIME type for WASM
    types {
        application/wasm wasm;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
